spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vic
    username: postgres
    password: password

  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: create-drop
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.ecommerce.vic: DEBUG
